spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: Nani@2425
    
  #jpa:
    #show-sql: true
    #hibernate:
      #ddl-auto: update
  #application:
     #name: DATA-SERVICE
     
server:
  port: 8081
  


